name: Staging Pipeline

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging-print-secret:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secret
        run: echo "Test Secret is ${{ secrets.SERVER }}" |
          echo "Variable env IS $USERNAME"
