name: Staging Pipeline

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging-print-secret:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      USERNAME: ${{ vars.USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
