name: Master CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/staging/**'

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secret
        run: |
          echo "Secret is ${{ secrets.SERVER }}" |
          echo "Test completed. $USERNAME"
