name: Staging Pipeline

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging-print-secret:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      USERNAME: ${{ vars.USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Debug - List environment variables
        run: printenv   

      - name: Debug - List environment variables
        run: |
          printenv | sort
          echo "USERNAME from env: ${{ env.USERNAME }}"

      - name: Print secret and variable
        run: |
          echo "Test Secret is [SECRET REDACTED]"
          echo "Variable env IS $USERNAME"
