name: Staging Pipeline

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging-print-secret:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Debug - List environment variables
        run: printenv

      - name: Print secret and variable
        run: |
          echo "Test Secret is [SECRET REDACTED]"
          echo "Variable env IS $USERNAME"
