name: Master CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/staging/**'

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment: Master
    if: github.event.before == 'refs/heads/staging'
    env:
      USERNAME: ${{ vars.USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secret
        run: |
          echo "Secret is ${{ secrets.SERVER }}"
          echo "Test completed. $USERNAME"
