name: Master CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths-ignore:
      - '**/staging/**'

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment: Master
    if: github.event.before == 'refs/heads/staging' && github.event.pull_request.merged == true
    env:
      USERNAME: ${{ vars.USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secret
        run: |
          echo "Secret is ${{ secrets.SERVER }}"
          echo "Test completed. $USERNAME"
